In [11]:
from glob import glob
import numpy as np
import os

In [19]:
with open('../results/results_w_top_features/xgbClassifier_kw_False_sachsen[confusion_matrix].txt') as f:
    lines = f.read()

[[10  3  4  3 13 16 17]
 [ 3 11  3  9  1 31 13]
 [ 4  3  1  3  0  6  9]
 [ 1  4  3  9  3 48 18]
 [ 7  4  2  6 21  9 42]
 [11 29  3 42  0 21 18]
 [ 6 10  8 12 13 22 50]]


In [17]:
cm

array([1.42644430e-153, 4.16304653e-062, 9.50076221e-259, 1.28223030e-153,
       4.56345996e-072, 9.49568104e-259, 1.42644431e-153, 6.96324776e-077,
       9.50321844e-259, 1.50102771e-153, 1.95999113e-062, 9.50203251e-259,
       1.50102773e-153, 1.02588539e-071, 9.49442564e-259, 1.87918889e-153,
       6.96324168e-077, 9.50203251e-259, 1.20764691e-153, 4.16304307e-062,
       5.56143594e+141])

In [8]:
for cm_file in glob('../results/results_w_top_features/*confusion_matrix*'):
    with open(cm_file) as f:
        f.read()

['../results/results_w_top_features/xgbClassifier_kw_False_sachsen[confusion_matrix].txt',
 '../results/results_w_top_features/xgbClassifier_wikikw_False_hamburg[confusion_matrix].txt',
 '../results/results_w_top_features/xgbClassifier_kw_False_bayern[confusion_matrix].txt',
 '../results/results_w_top_features/xgbClassifier_babelkw_False_thueringen[confusion_matrix].txt',
 '../results/results_w_top_features/xgbClassifier_kw_False_brandenburg[confusion_matrix].txt',
 '../results/results_w_top_features/xgbClassifier_kw_False_schleswig-holstein[confusion_matrix].txt',
 '../results/results_w_top_features/xgbClassifier_babelkw_False_rheinland-pfalz[confusion_matrix].txt',
 '../results/results_w_top_features/xgbClassifier_babelkw_False_saarland[confusion_matrix].txt',
 '../results/results_w_top_features/xgbClassifier_kw_False_saarland[confusion_matrix].txt',
 '../results/results_w_top_features/xgbClassifier_babelkw_False_sachsen-anhalt[confusion_matrix].txt',
 '../results/results_w_top_featu